name: Publish

on:
  push:

jobs:

  check-style:
    name: Check style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install poetry
        poetry config virtualenvs.create false --local
        poetry install
    - name: Check imports
      run: |
        isort --profile black --float-to-top --check-only svg_collector/main.py
    - name: Check formatting
      run: |
        black --line-length 120 --check svg_collector/main.py

  publish:
    name: Publish
    needs: check-style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install poetry
        poetry config virtualenvs.create false --local
        poetry install
    - name: Publish
      run: |
        poetry build
        poetry publish
